# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v2.3.2
     - uses: Azure/login@v1
       with:
         creds: ${{secrets.AZURE_CREDENTIALS}}

     # Runs a single command using the runners shell
     - name: Azure PostgreSQL Action
       uses: Azure/postgresql@v1
       with:
          # Server name of Azure DB for PostgreSQL. Example: fabrikam.postgres.database.azure.com
          server-name: rekpostlab.postgres.database.azure.com
          # The connection string, including authentication information, for the Azure PostgreSQL Server. Please provide psql connection string. Example: psql "host={host} port={port} dbname={your_database} user={user} password={your_password} sslmode=require"
          connection-string: psql "host=rekpostlab.postgres.database.azure.com port=5432 dbname={your_database} user=sqladmin@rekpostlab password={your_password} sslmode=require"
          # Path to PL/SQL script file to deploy. To specify multiple files, use the regex syntax : *.sql or folder/x/<regex>.sql
          plsql-file: data.sql
  
        
